all:
  hosts:
    nr-hv-dcpve-01:
    nr-hv-dcpve-02:
    nr-hv-dcpve-03:
    nr-hv-homepve-01:
    nr-hv-mgmtpve-01:
    nr-rt-edge-01:
    nr-sv-grafana-01:
    nr-sw-core-01:
    nr-sw-core-02:
    os-vps-01:
  children:
    junos:
      hosts:
        nr-sw-core-01:
        nr-sw-core-02:
    pve:
      hosts:
        nr-hv-dcpve-01:
        nr-hv-dcpve-02:
        nr-hv-dcpve-03:
        nr-hv-homepve-01:
        nr-hv-mgmtpve-01:
    univerge_ix:
      hosts:
        nr-rt-edge-01:
