__grafana_prerequisite_packages:
  - apt-transport-https
  - wget
  - gnupg
__grafana_gpg_key_url: https://apt.grafana.com/gpg-full.key
__grafana_keyring_path: /etc/apt/keyrings/grafana.asc
__grafana_apt_repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
__grafana_package_name: grafana
__grafana_service_name: grafana-server
